### ISSUE TITLE
More explaination

### ISSUE THREAD

**Issue by janhelleman** [Yahasana/kohana-oauthz#1]
Hi,

is there any chance you give us a bit more information about how your system works? The demo's don't really illustrate 'real life' situations and the way you have setup the DB is not really explained. What is the difference between a server and a client? What are audits? How would we implement an end-user authorization system in it?

Don't take my questions the wrong way, you are doing a great job, only I just don't get your method :)

Jan

**Comment by janhelleman** [comment]
To expand my comment, if servers are 'end users' then why do they have a 'client_secret' and 'client_id'? sounds more like server_secret and server_id. Further there should be a client_secret in clients right?

further I'd call a server a user since server sounds more like a hosting server :-)

**Comment by Yahasana** [comment]
The draft 10 remove signature section. and I think it's not a maturity protocal. there's so many problem behide. I'm waiting the final release.

**Comment by Yahasana** [comment]
The information that server shold hold:
a, the resource owner (system users) information
b, the authorized thirth-part client (maybe users themself).

the client request the resource owned by other users:
1, request and authorize code, access token (if accessible)
2, request the resource by the access token.

I'm try to offer more options to control these process flows, the DB model isn't the final one. I must say that the workflow in draft 10 isn't clear as its predecessor. and I have no idea why it hasn't updated for the last three months. 

There're many debate in the team and hard to reach consensus? I don't know.

for more information, please see http://hueniverse.com/

**Comment by Yahasana** [comment]
One more I want to say, I'm also waiting the Kohana 3.1, it maybe offer some more flexiable request information in the core lib. and I do not need to do it by this module itself. not yet make a final decision.

I'm much more take care the server part too, the client part isn't as important as it. because people may use other lib or even languages to request the resource holded by the server. they don't have to rely on Kohana or php to make it.

I do need some feedback, thanks

**Comment by janhelleman** [comment]
Ok I would love to guide you through while you develop, as I have a lot of interest in this feature. I want to get a server running up asap for a project I have, and your lib looks promising since I love kohana. You are right about the client side of it all, it's mostly nice to simply be able to test the whole picture. 

First notice feedback on the server side:
- You implemented the grant type "end user credentials" but you translate it as client credentials. The username and password are specifically for when the client has access to the end-user's credentials as far as I understand http://tools.ietf.org/html/draft-ietf-oauth-v2-10#section-4.1.2. 

quote: "   The client includes the resource owner credentials using the
   "password" access grant type and the following parameters: [[ add
   internationalization consideration for username and password ]]"

With that I think you mixed up the workings of the whole picture. As far as I understand your naming, the server = the end-user and the client = the one that requests the tokens and data/access. With the mistake I just mentioned I think you mixed up the client_secret, it belongs in the table client where in the table server (user) you need a server_secret or client_secret. Or not have the server_secret and leave that reference for another module to handle user login etc.
- Why does a server have a redirect_uri and a scope? They serve, don't pull, right? What's the use of it then? The only one redirected according to the spec, is when the user has to authorize the request at the server's end-point, but then the client redirect uri has to be used from the clients table, not the one from the server table. I don't see any use of it personally.
- You mix the use of reference of the oauth 1.0 and 2.0 spec in your naming while 2.0 spec use specific naming. You have end-users (users for example) and clients. You right now name end-users servers, which is a term of oauth 1.0 where clients where consumers. I'd refer from using server.

Don't take my feedback as hard as it sounds, the lib is great, I just don't think you understood it fully maybe. I might also be wrong sometimes, but I read the spec 4 times to understand it's working. I wanted to start such a lib, but due to personal health am unable to. Further I'd register it with the kohana-universe and request a notion on the oauth 2.0 site. When you get me more demo's examples etc, code updates whatever I'd love to go through with helping you since, as I told, I am really interested in this lib.

Jan

**Comment by janhelleman** [comment]
Damn I closed it, sorry. We can further discuss it at the kohana site as well, if you want. You decide!

**Comment by Yahasana** [comment]
1), The server is the resource holder, the client is the resource requester and the user is the resource owner.

the client have to tell the server where the server should redirect the end-users to when the client get the access token successfully. and the scope define what kind of the scopes are permitted. e.g. friends,contact?

2) I did have implemented oauth 1.0, but not put out as opensource. and this one is a rewrote base on that. I have not cleared some unnecessary fields yet ;). some of them will not be removed because I think there're good features.

I also believe it should be a good implement, haha. I'm trying hard to let it elegant and simple to deploy. because i want to implement a good web service API for my application platform. you can take this concept from readme. just simply extends your API class from `Oauth_Controller`, and then your API will be protected, no more need to do.

**Comment by janhelleman** [comment]
I don't fully get your respond on point one, since the main reason I made that point is the way you implement 4.1.2. This grant type is created for the client to access the resource of the resource owner by getting an access token based on the end-user's credentials as I quoted from the latest draft. I'll reqoute :-)

 " The client includes the resource owner credentials using the
"password" access grant type and the following parameters: [[ add internationalization consideration for username and password ]]"

Section 4.1.1 and 4.1.2 show the difference in the whole. The first is authorization through an auth token and the client_id and client_secret. The second credential grant type uses the resources owners username and password. So I really think you mixed up some parts here. This is from the 4.1.1 section:

   o  Validate the client credentials (if present) and ensure they match
      the authorization code.

   o  Verify that the authorization code and redirection URI are all
      valid and match its stored association.

This is from section 4.1.2:

   The authorization server MUST validate the client credentials (if
   present) and end-user credentials and if valid issue an access token
   response as described in Section 4.2.

Please keep asking me things and I will give you feedback cause this will just make the whole lib 100% better.

There's no harm done that u used a previous layout from the 1.0 spec. But please supply some form of explaination for the fields you mention, and I'd advice you to rethink your naming such as the client_secret in the server table. 

Please tell me if you get what I mean above

**Comment by Yahasana** [comment]
Resource Owner's information is held by t_oauth_clients. it's identified by user_id (#Ref from users table). when resource requester ask him to request something. e.g. contact, t_oauth_clients will record the requester's redirect_uri,scope and other information. client_level limit this resource only to be requested in how many times, which is not in the core reference.

The t_oauth_servers controls the resource requester behavior. first he should ask the server what kind of redirect_uri is his website and what kind of scope he can request. you even can control them  by manual review (recommend).

I do not take the `Resource Owner Password Credentials` into account in here, it's just another login interface (the username and password may be stored in users table)

**Comment by janhelleman** [comment]
I would really advice you to rethink your naming structure. The oauth 2.0 spec identifies the client as the resource requester and the user as the resource owner. I hope you will implement the resource owner password credentials, and if not, you should not handle that grant type in a different way then as it is meant to be, to verify the resource owner credentials, not the resource requester credentials. To be honest I am very confused about your implementation mostly because you seem to mix up a lot of naming in comparison to the specification draft, which I personally find very confusing :-)

See paragraph 1.2 for terminology (http://tools.ietf.org/html/draft-ietf-oauth-v2-10#section-1.2)

**Comment by Yahasana** [comment]
Yes, it does confuse me too. I have been starting this lib from draft 4, and there're many part of the specification changing time and time again. that's why I stop to update to complete match with draft 10. I'm tired of it. I think (predict) there will be a dramatically change in the final release. if you compare rev 8, 9, 10. you may find some ridicule modification. I pause and rethink what you recommendation. thanks

**Comment by janhelleman** [comment]
I personally wouldn't pause if I were you, but that's just me. I would first redo all the database layout scheme towards something that compromises to the scheme I said before about client being consumer and user being server (data owner). Further I would personally try to implement the grant types in the right ways. If you have any form of IM like msn or gtalk I would gladly help you talk through?

**Comment by Yahasana** [comment]
come on man, I do not mean I'll quit. after long time await from this, I'll refactor the code and make it work like a charm. sometime you need to take a nap for thinking better. I did update the scheme, but do not commit into the master yet. the current model implement is just for simple data handling, too far from production using. 

I'm plan to restart in this weekend.

**Comment by janhelleman** [comment]
Yea great I don't mean I thought you'd quit but I just thought that talking through an IM like gtalk or msn would be faster in terms of communication and understanding :)

**Comment by janhelleman** [comment]
Its fine communicating through here as well, I just thought I'd be more of a help if we could communicate a bit more direct.

Let me know when you commit anything new or need a help on something, I will comment on it.

**Comment by janhelleman** [comment]
Hey man,

any chance you were going to refactor those db items such as server and client? Cause I personally am still confused, maybe you can enlighten me?

Client should be client == consumer in oauth 1.0, or better said, the one requesting a resource

User == end user == server in oauth 1.0, better said the resource owner 

why does the server table have a client_secret field? The name just doesn't make sence to me :-) Client_secret as described in the docs is the password or secret of the resource requester. The secret you are refering to, is the user password and user name, which i repeatedly linked you to in section 4.1.2.

Please try and explain to me if I don't get it :-)

**Comment by kanema** [comment]
Hi! you can make a package with a demo application, please?

Tks!

**Comment by Yahasana** [comment]
There's semi-demo in the package

**Comment by kanema** [comment]
Sorry, I was not able to run the application.
Thanks

**Comment by janhelleman** [comment]
What kind of demo are you thinking of?

**Comment by janhelleman** [comment]
it is all still very confusing. Client is supposed to be the user right? in the docs client is the resource requesting application. Server is translated to doc codes the user serving the data?

It's confusing. Sorry. I thought you'd make some examples or at least explain some more about the workings of your implementation

**Comment by Yahasana** [comment]
draft 11 is out, I'm goin' to adopt to it. 

the current implement demo is ONLY for web server flow:
1) the client(sever host application) request a authorize code and ask the end user to approve its.
2) the client request an access token if the end user approves
3) the client request the resource by access token

i have no more time to write some more detail doc to describe these flow ATM, please read the reference yourself. I think they are more clear now.

**Comment by janhelleman** [comment]
When do you think your demo's will be more self explaining?

**Comment by Yahasana** [comment]
I think the newest rev draft is much more clear to understand, though it's still a little far from perfect.

time to close this issue.
