### ISSUE TITLE
Class names

### ISSUE THREAD

**Issue by janhelleman** [Yahasana/kohana-oauthz#2]
Hi,

I was wondering if you could rename your classes. I started using your lib but have to use oauth 1.0 lib as well. The oauth 1.0 module uses names like oauth_token as well (the one that comes with kohana) and yours to. This creates conflicts. I'd like to ask you to name all your classes something like Oauth2_Token, because you are making an oauth2.0 lib. I am currently working on a little facebook login, and it works good man.

when i have something bigger I will let you know ok? Let me know if you can help me, would hate to rename all my files everytime you update your code :)

**Comment by Yahasana** [comment]
I'm planing to make sure these classes do not conflict with other ones from different libs.

the client part of these lib have not finished, and only for testing the oauth server. but I'm very glad it does work for you.

thank you very much for reporting issues you found. I do need some guys to help me knock out all the bugs. that save my time and you too.

There're some files with unsuitable name when they ware created, and I have to rename them for more clear. I'm sorry for that. they are going to be stable now.

**Comment by janhelleman** [comment]
How can I give you source code I make ?

**Comment by Yahasana** [comment]
feel free to fork this project and pull your commit request

**Comment by janhelleman** [comment]
I made a fork and renamed everything I think. All class names that were Oauth_ etc are now Oauth2_ .. etc. Please check it man, it now works with kohana's oauth 1.0 lib.

**Comment by Yahasana** [comment]
Good work! would you please send a pull request of your commit, thanks

**Comment by janhelleman** [comment]
Did I send you one now? I am new to github...

**Comment by Yahasana** [comment]
Landed https://github.com/Yahasana/OAuth-2.0/commit/8ad32761d4c87e5612ddceaefc530cbfc5c74c7b
